In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("Visit-Nominal.csv", sep=",")

In [30]:
df

Home Browsed Searched Prod_A Prod_B Prod_C Visit_Again
0   yes      no       no     no     no     no          no
1   yes     yes      yes     no     no     no          no
2   yes      no       no     no     no     no          no
3   yes     yes      yes    yes     no     no         yes
4   yes      no      yes    yes    yes     no         yes
5   yes     yes      yes     no    yes     no          no
6   yes      no      yes     no     no     no         yes
7   yes      no      yes     no    yes     no          no
8   yes     yes      yes     no    yes     no          no
9   yes      no      yes    yes    yes    yes         yes
10  yes      no      yes    yes    yes    yes          no
11  yes      no      yes    yes     no    yes          no
12  yes      no      yes    yes     no     no         yes
13  yes     yes      yes     no     no    yes          no
14  yes      no      yes    yes    yes    yes          no
15  yes     yes      yes    yes    yes     no         yes
16  yes      no      yes     no     no     no         yes
17  yes      no      yes     no     no     no          no
18  yes     yes       no    yes    yes     no          no
19  yes      no       no    yes     no     no          no
20  yes     yes      yes     no     no    yes         yes
21  yes      no      yes     no     no    yes         yes
22  yes     yes       no     no     no     no          no
23  yes     yes       no    yes     no     no          no
24  yes     yes       no    yes    yes    yes          no
25  yes     yes      yes     no    yes    yes          no
26  yes     yes       no    yes    yes    yes          no
27  yes     yes       no    yes    yes     no          no
28  yes     yes      yes    yes    yes    yes          no
29  yes     yes       no    yes    yes    yes          no
..  ...     ...      ...    ...    ...    ...         ...
70  yes     yes      yes    yes     no    yes         yes
71  yes     yes       no    yes    yes     no         yes
72   no      no       no    yes     no     no         yes
73  yes      no       no    yes     no     no          no
74  yes      no       no    yes     no    yes         yes
75   no     yes       no    yes     no     no         yes
76   no      no       no    yes     no     no          no
77  yes     yes      yes    yes     no    yes         yes
78  yes     yes       no    yes     no     no         yes
79   no      no       no    yes    yes     no          no
80   no      no       no    yes     no     no         yes
81   no      no       no    yes    yes     no         yes
82   no     yes      yes     no    yes     no          no
83   no     yes       no     no    yes    yes         yes
84   no     yes       no     no    yes    yes          no
85   no     yes       no     no    yes    yes          no
86   no     yes       no     no    yes    yes          no
87   no     yes       no     no    yes    yes         yes
88   no     yes       no     no    yes    yes          no
89   no     yes      yes     no    yes    yes          no
90   no     yes       no     no    yes    yes         yes
91   no     yes       no     no    yes    yes         yes
92   no     yes      yes     no    yes     no          no
93   no     yes       no     no    yes    yes         yes
94   no     yes       no     no    yes    yes          no
95   no     yes       no     no    yes    yes          no
96   no     yes       no     no    yes    yes         yes
97   no     yes       no     no    yes    yes         yes
98   no     yes       no     no    yes    yes          no
99   no     yes      yes     no    yes    yes          no

[100 rows x 7 columns]

In [31]:
import numpy as np

In [32]:
df.Visit_Again.size

100

In [33]:
target_names = np.array([1,0])

In [34]:
targets = np.array([])

In [35]:
df.Home[df.Home == 'yes'] = 1
df.Home[df.Home == 'no'] = 0
df.Browsed[df.Browsed == 'yes'] = 1
df.Browsed[df.Browsed == 'no'] = 0
df.Searched[df.Searched == 'yes'] = 1
df.Searched[df.Searched == 'no'] = 0
df.Prod_A[df.Prod_A == 'yes'] = 1
df.Prod_A[df.Prod_A == 'no'] = 0
df.Prod_B[df.Prod_B == 'yes'] = 1
df.Prod_B[df.Prod_B == 'no'] = 0
df.Prod_C[df.Prod_C == 'yes'] = 1
df.Prod_C[df.Prod_C == 'no'] = 0
df.Visit_Again[df.Visit_Again == 'yes'] = 1
df.Visit_Again[df.Visit_Again == 'no'] = 0

In [36]:
for i in range(df.Visit_Again.size):
    if df.Visit_Again[i] == 1:
        targets = np.append(targets,1)
    else:
        targets = np.append(targets,0)

In [37]:
targets

array([0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.])

In [38]:
df['is_train'] = True

In [39]:
for i in range(df.Visit_Again.size):
    if i<30:
        df['is_train'][i]=False

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [40]:
df['Type'] = pd.Categorical.from_codes(targets, target_names)

In [41]:
df['Targets'] = targets

In [42]:
train = df[df['is_train']==True]

In [43]:
test = df[df['is_train']==False]

In [44]:
trainTargets = np.array(train['Targets']).astype(int)

In [45]:
testTargets = np.array(test['Targets']).astype(int)

In [46]:
features = df.columns[0:6]

In [47]:
from sklearn.naive_bayes import GaussianNB

In [48]:
gnb = GaussianNB()

In [49]:
y_gnb = gnb.fit(train[features], trainTargets).predict(test[features])

In [50]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
mnb = MultinomialNB()

In [52]:
y_mnb = mnb.fit(train[features], trainTargets).predict(test[features])

In [53]:
from sklearn.naive_bayes import BernoulliNB

In [54]:
bnb = BernoulliNB()

In [55]:
y_bnb = bnb.fit(train[features], trainTargets).predict(test[features])

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
print(y_gnb)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1]


In [58]:
print(accuracy_score(testTargets, y_gnb))

0.4666666666666667


In [59]:
print(y_mnb)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1]


In [60]:
print(accuracy_score(testTargets, y_mnb))

0.4666666666666667


In [61]:
print(y_bnb)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1]


In [62]:
print(accuracy_score(testTargets, y_bnb))

0.4666666666666667
